### DISCUSSION TITLE
Instant Backup | Stash

### DISCUSSION THREAD

**Discussion by giscus** [appscode/community#48] [Stash]
# Instant Backup | Stash

Instant Backup This guide will show you how to take an instant backup in Stash.
Before You Begin At first, you need to have a Kubernetes cluster, and the kubectl command-line tool must be configured to communicate with your cluster. If you do not already have a cluster, you can create one by using kind.
Install Stash in your cluster following the steps here.
You should be familiar with the following Stash concepts:

https://stash.run/docs/v2023.01.05/guides/use-cases/instant-backup/

**Comment by JcGKitten** [comment]
Documentation is outdated:
The BackupSession needs 
```yaml
metadata:
  lables:
    stash.appscode.com/invoker-type: <BackupConfiguration/BackupBatch kind>
    stash.appscode.com/invoker-name: <BackupConfiguration/BackupBatch name>
```
